// JBoss, Home of Professional Open Source
// Copyright 2016, Red Hat, Inc. and/or its affiliates, and individual
// contributors by the @authors tag. See the copyright.txt in the
// distribution for a full listing of individual contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

### Deploy hola (JAX-RS/Wildfly Swarm) microservice

#### Deploy project via oc CLI

##### Basic project creation

----
$ git clone https://github.com/redhat-helloworld-msa/hola
$ cd hola/
$ oc new-build --binary --name=hola -l app=hola
$ mvn package; oc start-build hola --from-dir=. --follow
$ oc new-app hola -l app=hola,hystrix.enabled=true
$ oc expose service hola
----

##### (Optional) Enable Readiness probe

----
$ oc set probe dc/hola --readiness --get-url=http://:8080/api/health
----

////

#### Option 2: Deploy using Fabric8 plugin

Execute:

----
$ git clone https://github.com/redhat-helloworld-msa/hola
$ cd hola/
$ mvn clean package docker:build fabric8:json fabric8:apply
----



### Option 3: Deploy project using WildFly-Swarm builder template/imagestream

----
$ oc login 10.1.2.2:8443 (login with openshift-dev/devel credentials)
$ oc project helloworld-msa
$ oc create -f https://raw.githubusercontent.com/wildfly-swarm/sti-wildflyswarm/master/1.0/wildflyswarm-sti-all.json
$ oc logs -f bc/wildflyswarm-10-centos7-build
----

#### Option 3.1 - Using oc CLI

Execute:

----
$ oc new-app --name hola wildflyswarm-10-centos7~https://github.com/redhat-helloworld-msa/hola -l app=hola,hystrix.enabled=true
$ oc expose service hola
$ oc logs -f bc/hola
----

#### Option 3.2 - Using Openshift console

- Click `"Add to Project"`
- Select `"wildflyswarm-10-centos7"` image 
- Name: `hola`
- Git URL: https://github.com/redhat-helloworld-msa/hola
- Click on `"Show advanced build and deployment options"`
- Add the label **hystrix.enabled** with the value **true**
- Click on `"Create"`. And them click on `"Continue to overview"`
- Wait for the build to complete. (You can click `"View log"` to follow the build logs)

////

#### Test the service endpoint

Access: http://hola-helloworld-msa.rhel-cdk.10.1.2.2.xip.io/api/hola
