// JBoss, Home of Professional Open Source
// Copyright 2016, Red Hat, Inc. and/or its affiliates, and individual
// contributors by the @authors tag. See the copyright.txt in the
// distribution for a full listing of individual contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

## Prepare Environment

### Install Openshift Client

You can download and unpack the CLI from the link:https://github.com/openshift/origin/releases/tag/v1.3.0[Github] for use on Linux, MacOSX, and Windows clients. 


### (Option 1) Use CDK (OpenShift Container Platform 3.2)

- Install a virtualization provider (hypervisor) for your system such as VirtualBox, VMware, or KVM/libvirt.
- Install Vagrant, from link:https://www.vagrantup.com/[vagrantup.com], or from your operating system’s packages.
- From link:http://developers.redhat.com/products/cdk/download/[Red Hat CDK Download page] download Red Hat Container Tools (cdk-2.2.0.zip) and the RHEL 7.2 Vagrant box that matches your virtualization provider: VirtualBox, VMare, or KVM/libvirt.
- Unzip `cdk-2.2.0.zip` into a directory of your choosing.

Install the required vagrant plugins:

----
$ vagrant plugin install vagrant-service-manager vagrant-registration vagrant-sshfs
----

Add the RHEL 7.2 Vagrant box to Vagrant with the command:

----
$ vagrant box add --name cdkv2 <path to downloaded .box file>
----

Update CDK Memory and CPU

----
$ cd <CDK-PATH>/components/rhel/rhel-ose
$ export VM_MEMORY=6000
----

Execute Vagrant:

----
$ export SUB_USERNAME=<your-subscription-username>
$ export SUB_PASSWORD=<your-subscription-password>
$ vagrant up
----

#### Access Openshift console

Open Openshift console:  https://10.1.2.2:8443/console/ +
(Accept the certificate and proceed)

Log in Openshift +
Use **openshift-dev/devel** as your credentials

### (Option 2) Use "oc cluster up" (OpenShift Container Platform 3.3)

This option only needs a link:https://github.com/docker/machine/releases[docker-machine] installed.

Execute:

----
$ oc cluster up --create-machine=true   \
                --use-existing-config   \
                --host-data-dir=/mydata \
                --image=registry.access.redhat.com/openshift3/ose \
                --version=latest
----

#### Access Openshift console

Open Openshift console:  https://<openshift_ip>:8443/console/ +
(Accept the certificate and proceed)

Log in Openshift +
Use **openshift-dev/devel** as your credentials

////

### (Option 2) Use minishift

Download link:https://github.com/jimmidyson/minishift[minishift] and install its link:https://github.com/jimmidyson/minishift#installation[requirements].

To start openshift, execute:

----
$ minishift start --cpus=2 --deploy-router=true --memory=6000
----

////
